### ISSUE TITLE
Add lumi.acpartner.mcn02 (KTBL03LM) support

### ISSUE THREAD

**Issue by RolabHJ** [syssi/xiaomi_airconditioningcompanion#80] opened 2019-09-04 15:02 UTC
2019-09-04 15:54:28 INFO (MainThread) [custom_components.xiaomi_miio_airconditioningcompanion.climate] lumi.acpartner.mcn02 1.3.2_108 ESP32 detected
2019-09-04 15:54:29 DEBUG (SyncWorker_11) [miio.protocol] Unable to decrypt, returning raw bytes: b''
2019-09-04 15:54:29 DEBUG (SyncWorker_11) [miio.device] Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x04m\xad\xd3]o\xd0$' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = b'\x04m\xad\xd3' (total 4)
            ts = 2019-09-04 14:54:28
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
2019-09-04 15:54:29 DEBUG (SyncWorker_11) [miio.device] Discovered 046dadd3 with ts: 2019-09-04 14:54:28, token: b'ffffffffffffffffffffffffffffffff'

**Comment by RolabHJ** [comment] 2019-09-04 15:28
KTBL03LM

**Comment by s614053620** [comment] 2019-09-04 16:19
咱俩问题好像差不多

**Comment by apast1** [comment] 2019-09-14 18:31
also same question

**Comment by fireinice** [comment] 2020-10-29 08:39
[dup issue](https://github.com/syssi/xiaomi_airconditioningcompanion/issues/61)

**Comment by syssi** [comment] 2020-10-29 08:43
Duplicate of #61.

**Closed by syssi** 2020-10-29 08:43 UTC
