### ISSUE TITLE
Could you support KTBL03LM ?

### ISSUE THREAD

**Issue by EzrealCdev** [syssi/xiaomi_airconditioningcompanion#68] opened 2019-07-20 17:38 UTC
Xiaomi Mi Air Conditioner Companion 2

**Comment by bluefoxlee** [comment] 2019-07-21 18:17
I believe this is same issue as [#61](https://github.com/syssi/xiaomi_airconditioningcompanion/issues/61) .

**Comment by syssi** [comment] 2019-08-08 13:37
Duplicate of #61. Please follow this issue.

**Closed by syssi** 2019-08-08 13:37 UTC
