### ISSUE TITLE
Add lumi.acpartner.mcn02 support

### ISSUE THREAD

**Issue by MagicInstall** [syssi/xiaomi_airconditioningcompanion#85] opened 2019-10-12 13:28 UTC
firmware up to 2.0.6_0004

2019-10-12 21:21:34 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_airconditioningcompanion which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-10-12 21:21:45 ERROR (MainThread) [custom_components.xiaomi_miio_airconditioningcompanion.climate] Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}
2019-10-12 21:22:50 ERROR (MainThread) [custom_components.xiaomi_miio_airconditioningcompanion.climate] Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}

**Comment by Clansty** [comment] 2019-12-09 10:58
我也是  
Me too.

我的固件版本是 2.0.6_0006  
My framework version is 2.0.6_0006

**Comment by pznamenskii** [comment] 2020-02-10 11:04
2020-02-10 14:00:07 INFO (MainThread) [custom_components.xiaomi_miio_airconditioningcompanion.climate] lumi.acpartner.mcn02 2.0.6_0006 esp32 detected
2020-02-10 14:00:07 DEBUG (SyncWorker_2) [miio.device] 192.168.1.183:54321 >>: {'id': 2, 'method': 'get_model_and_state', 'params': []}
2020-02-10 14:00:11 DEBUG (SyncWorker_2) [miio.device] 192.168.1.183:54321 (ts: 1970-01-01 00:37:43, id: 2) << {'id': 2, 'error': {'code': -9999, 'message': 'user ack timeout'}}
2020-02-10 14:00:12 ERROR (MainThread) [custom_components.xiaomi_miio_airconditioningcompanion.climate] Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}

**Comment by syssi** [comment] 2020-11-01 10:33
Duplicate of #61

**Closed by syssi** 2020-11-01 10:33 UTC
Labels: new-device
