### ISSUE TITLE
ERROR Unable to update from sensor

### ISSUE THREAD

**Issue by SPEC1AL1ST** [syssi/xiaomi_airconditioningcompanion#148] opened 2022-04-08 07:47 UTC
core-2022.4.1
Home Assistant OS 7.6
2022-04-08 10:40:08 ERROR (MainThread) [custom_components.xiaomi_miio_airconditioningcompanion.climate] Unable to update from sensor: could not convert string to float: 'unavailable'

Logger: custom_components.xiaomi_miio_airconditioningcompanion.climate
Source: custom_components/xiaomi_miio_airconditioningcompanion/climate.py:277
Integration: xiaomi_miio_airconditioningcompanion ([documentation](https://github.com/syssi/xiaomi_airconditioningcompanion), [issues](https://github.com/syssi/xiaomi_airconditioningcompanion/issues))
First occurred: 10:40:08 (1 occurrences)
Last logged: 10:40:08

Unable to update from sensor: could not convert string to float: 'unavailable'

**Comment by syssi** [comment] 2022-04-23 18:08
Duplicate of  #144

**Closed by syssi** 2022-04-23 18:08 UTC
